spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa11
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true #system.out을 통해 출력
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug    #log를 통해 출력
    org.hibernate.type: trace